name: generate plantuml

on:
  pull_request:
    branches: 
      - develop
      - release/*
      - hotfix/*
    types:
      - opened
      - edited
      - synchronize

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
      - name: plantuml
        id: plantuml
        uses: b97390022/generate-plantuml-action@master
        with:
          path: .
          message: "Render PlantUML files."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}