name: generate plantuml

on:
  workflow_run:
    workflows: ["Lint PR"]
    types:
      - completed

jobs:
  generate_plantuml:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: plantuml
        id: plantuml
        uses: b97390022/generate-plantuml-action@master
        with:
          path: .
          message: "Render PlantUML files."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}