name: generate plantuml

on: 
  push:
    branches: 
      - develop

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: plantuml
        id: plantuml
        uses: b97390022/generate-plantuml-action@master
        with:
          path: .
          message: "Render PlantUML files."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}