name: generate plantuml

on: 
  push:
    branches: 
      - develop

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@ae213c00d5c2c2de1fd8642055bcf571fea2f72e
        with:
          path: .
          message: "Render PlantUML files."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}